version: 0.2 
 
env: 
  variables: 
    TF_VERSION: "1.5.0" 
 
phases: 
 
  install: 
    commands: 
      - cd /usr/bin 
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" 
      - unzip -o terraform.zip 
 
  build: 
    commands: 
      - terraform init -no-color
      - terraform plan -no-color 
      - terraform apply --auto-approve
 
  post_build: 
    commands: 
      - echo "deployment complete"
